databases:
  - name: smilink
    databaseName: smilink
    user: smilink_user

services:
  - type: web
    name: samilink
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smilink
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: smailink.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://smailink.onrender.com
